// utils/data.js —— 静态数据：分类（前端固定，与后端 categoryId 软映射），
// 以及离线/接口失败时的商品兜底。字段对齐 Prisma：mainImage / images。
const categories = [
  { id: 'tea', name: '茶器', sub: 'Tea Ware', desc: '一盏清茗，映照素心' },
  { id: 'vase', name: '花器', sub: 'Flower Ware', desc: '插一枝，便是四时' },
  { id: 'incense', name: '香炉', sub: 'Incense', desc: '焚香默坐，闲听风过' },
  { id: 'art', name: '艺术品', sub: 'Art Piece', desc: '案头雅物，一器一境' },
]

const products = [
  {
    id: 'p01',
    name: '云岫 · 青釉小壶',
    sub: '景德镇 · 手作',
    price: 1280,
    mainImage: '/images/product-teapot.jpg',
    images: ['/images/product-teapot.jpg', '/images/hero-celadon.jpg'],
    category: 'tea',
    tag: '孤品',
    intro: '取云岫之意，釉色青润温和。壶身手拉坯成型，釉面留有微妙气泡痕，每一件皆独一无二。',
    specs: ['容量 约 180ml', '尺寸 高 8cm 宽 11cm', '材质 高岭土·柴烧青釉'],
  },
  {
    id: 'p02',
    name: '素简 · 白瓷长颈瓶',
    sub: '龙泉 · 窑变',
    price: 860,
    mainImage: '/images/product-vase.jpg',
    images: ['/images/product-vase.jpg', '/images/product-vase2.jpg'],
    category: 'vase',
    tag: '限量',
    intro: '细长颈身，线条清瘦。釉面开片自然，适合一枝素花，亦可独立陈设。',
    specs: ['尺寸 高 26cm', '材质 瓷土·冰裂白釉', '适用 插花·陈设'],
  },
  {
    id: 'p03',
    name: '墨隐 · 灰釉圆炉',
    sub: '德化 · 柴窑',
    price: 1680,
    mainImage: '/images/product-incense.jpg',
    images: ['/images/product-incense.jpg'],
    category: 'incense',
    tag: '典藏',
    intro: '取静观之意，炉身饱满，釉色深沉若墨。适配线香、盘香，是案头之伴。',
    specs: ['尺寸 高 9cm 口径 12cm', '材质 陶土·哑光灰釉', '附赠 铜香插一枚'],
  },
  {
    id: 'p04',
    name: '止水 · 青瓷茶碗',
    sub: '台州 · 单杯',
    price: 420,
    mainImage: '/images/product-bowl.jpg',
    images: ['/images/product-bowl.jpg'],
    category: 'tea',
    tag: '',
    intro: '碗口微敞，釉面一道自然釉泪，冲泡时茶汤色泽尽显。',
    specs: ['容量 约 160ml', '尺寸 口径 9.5cm', '材质 瓷土·青釉'],
  },
  {
    id: 'p05',
    name: '空山 · 陶塑摆件',
    sub: '孤品 · 手作',
    price: 3200,
    mainImage: '/images/product-art.jpg',
    images: ['/images/product-art.jpg', '/images/hero-celadon.jpg'],
    category: 'art',
    tag: '孤品',
    intro: '以山为意，以空为念。自然抽象的造型，随光影流动呈现不同的表情。',
    specs: ['尺寸 高 22cm', '材质 粗陶·素烧', '说明 孤品·不可复制'],
  },
  {
    id: 'p06',
    name: '对影 · 青釉小盏·一对',
    sub: '景德镇',
    price: 680,
    mainImage: '/images/product-cup.jpg',
    images: ['/images/product-cup.jpg'],
    category: 'tea',
    tag: '',
    intro: '小盏两只，釉色如春水初生，适合分饮一壶茶，与人对影成双。',
    specs: ['容量 约 60ml × 2', '尺寸 高 4.5cm', '材质 瓷土·青釉'],
  },
  {
    id: 'p07',
    name: '寒枝 · 青瓷独枝瓶',
    sub: '龙泉',
    price: 520,
    mainImage: '/images/product-vase2.jpg',
    images: ['/images/product-vase2.jpg'],
    category: 'vase',
    tag: '',
    intro: '瓶身修长，仅容一枝寒梅或木本。釉色润如春水，光下见冰裂纹理。',
    specs: ['尺寸 高 28cm', '材质 瓷土·青釉', '适用 单枝插花'],
  },
]

module.exports = { categories, products }
